# Generated by Django 5.0.4 on 2024-05-23 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='blog.tag',null=True,blank=True),
        ),
    ]
