# Generated by Django 5.0.4 on 2024-05-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_blog_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_tag',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='post',
            name='blog_tag',
            field=models.ManyToManyField(to='blog.tag'),
        ),
    ]
