# Generated by Django 5.0.4 on 2024-05-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_post_blog_tag_alter_post_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(choices=[('CompSoc', 'CompSoc'), ('Diode', 'Diode'), ('Piston', 'Piston'), ('Aviation', 'Aviation')], max_length=50),
        ),
    ]
